version: "3"

services:
    jce_java:
        build: ./docker-jce-jre
        image: pronter/jce-java
        read_only: true
        command: echo "jce java"
        environment:
            - TZ=Asia/Shanghai
    eureka1:
        build: ./eureka-registry-ms
        image: prontera/eureka-registry-ms
        ports:
            - "8763:8763"
            - "9274:9274"
        depends_on:
            - 'jce_java'
        environment:
            - TZ=Asia/Shanghai
        command: "--spring.profiles.active=peer1"
    eureka2:
        build: ./eureka-registry-ms
        image: prontera/eureka-registry-ms
        ports:
            - "8762:8762"
            - "10177:10177"
        depends_on:
            - 'jce_java'
        environment:
            - TZ=Asia/Shanghai
        command: "--spring.profiles.active=peer2"
